services:
  - type: web
    name: gg-constructions
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 18.20.3
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
